### PR TITLE
scroll to offsets values. dy and dx required for Android.

### PR DESCRIPTION
**Pull request by SeanKelly369**
Allows scrolling offset of CollectionViews to be handler and updated outside of the CollectionView.  For example, syncing the positions of multiple CollectionViews.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@SeanKelly369 wouldn't it be better to have one method with both DX and dy? That way you could handle all cases

**Comment by SeanKelly369** [comment]
@farfromrefug Sure, that can be done if you want.

**Comment by farfromrefug** [comment]
@SeanKelly369 think it would be best if you could update the PR

**Comment by SeanKelly369** [comment]
I was thinking about this further.  ScrollView has these same functions.  Keeping the same names would make it easier for developers to change types.  With this in mind, wouldn't it make seen to have 3 functions in total?

**Comment by farfromrefug** [comment]
@SeanKelly369 good question. Honestly i would prefer collectionview to remain as fast and small as possible. we could pave the way for scrollview to follow in the future

**Comment by SeanKelly369** [comment]
Updated, but can it be tested before committing?

**Pull request merged**
